### PR TITLE
Add design and template for leaderboard

### PR DESCRIPTION
**Pull request by tawakuliKH**
In this branch :

- [ ] I added the template of leaderboard page

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @tawakuliKH 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7




## Highlights
 - [ ]  Correct GitFlow  ✅
 - [ ]  Good PR title/description  ✅
 - [ ]  All linters passed  ✅
 
## Required Changes ♻️
- [ ] Good job adding the MIT file, The problem is you need to update its content in regard to your name and this project. Please replace the `[YOUR NAME]` part with your name, `[APP TYPE]` with your app type, and the [YEAR] with the current year. 

_Check the comments under the review._

## Optional suggestions
- [Optional] Please try to be more descriptive in your pull request sumery. This is a place where you can introduce what changes you have made since the last merge. You can also specify any information that you would like to communicate with the code reviewer of the project.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tawakuliKH** [comment]
Hello @TadesseDev!
Please could you specify what changes is required!
I didn't get what is your point! :smiling_face_with_tear:

**Comment by TadesseDev** [comment]
Dear @tawakuliKH, Thanks for reaching out. Please update your [MIT file](https://github.com/tawakuliKH/Leaderboard/blob/simple-design/LICENSE). As you can see the year is `2021` and the owner of the project should be `your name` beside that Please consider changing the `software name` with your project name. We need to have a professional project that includes a valid [MIT](https://github.com/tawakuliKH/Leaderboard/blob/simple-design/LICENSE) licensed.

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @tawakuliKH, 

To highlight 👍🏽 
✔️ README is professional
✔️ No linter errors
✔️ App runs as expected

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
